version: '3.8'
services:
  jupyterlab_ai:
    image: devijlab:v1.1.0
    build:
      context: .
    # user: ${UID}:${GID}
    deploy:
      resources:
        limits:
          memory: 16384M
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
    volumes:
      - /home/devi/jupyterlab_docker/datasets:/datasets:ro
      - /home/devi/jupyterlab_docker/notebooks:/opt/app/data/
    ports:
      - '[::1]:8889:8889'
    # networks:
    #   - devijlab-net
    network_mode: bridge
    entrypoint: ["/usr/bin/python3.10", "/usr/local/bin/jupyter", "lab"]
    command: ["--ip=0.0.0.0", "--port=8889", "--notebook-dir=/opt/app/data", "--allow-root"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - HTTP_PROXY=http://172.17.0.1:8120
      - HTTPS_PROXY=http://172.17.0.1:8120
      - ALL_PROXY=socks5h://172.17.0.1:9001
      - NO_PROXY="localhost, 127.0.0.1, ::1"
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia
    restart: unless-stopped
    dns:
      - 9.9.9.9
      - 149.112.112.112
      - 2620:fe::fe
      - 2620:fe::9
volumes:
  devijlab-vault:
networks:
  devijlab-net:
    ipam:
      driver: overlay
      config:
        - subnet: 172.18.0.0/16
        - ip_range: 172.18.5.0.24
        - gateway: 172.18.0.1
